[pytest]
testpaths = tests/unit, tests/integration
python_files = test_*.py

markers =
    unit: unit tests (no external deps)
    integration: integration tests (db, redis, minio, http)

addopts =
    -ra
    --strict-markers
    --disable-warnings
    --maxfail=1

asyncio_mode = auto

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::RuntimeWarning
