from __future__ import annotations

import base64
import json
import os
import time
from typing import Any, Dict, Optional

import requests
from fastapi import APIRouter, Depends, Header, HTTPException
from minio import Minio
from minio.error import S3Error
from openai import OpenAI
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from apps.api.db import get_db
from apps.api.models import AIJob, Media

router = APIRouter(prefix="/v1", tags=["ai-internal"])


# ----------------------------
# Settings helpers
# ----------------------------
def _env_bool(name: str, default: bool = False) -> bool:
    v = (os.getenv(name) or "").strip().lower()
    if v in ("1", "true", "yes", "y", "on"):
        return True
    if v in ("0", "false", "no", "n", "off"):
        return False
    return default


def _require_internal_token(x_ai_internal_token: Optional[str]) -> None:
    token = (os.getenv("AI_INTERNAL_TOKEN") or "").strip()
    if not token:
        raise HTTPException(status_code=500, detail="AI_INTERNAL_TOKEN is not configured")
    if (x_ai_internal_token or "").strip() != token:
        raise HTTPException(status_code=401, detail="invalid ai internal token")


def _get_minio() -> Minio:
    endpoint = (os.getenv("MINIO_ENDPOINT") or "").strip()
    access = (os.getenv("MINIO_ACCESS_KEY") or "").strip()
    secret = (os.getenv("MINIO_SECRET_KEY") or "").strip()
    secure = (os.getenv("MINIO_SECURE") or "0").strip().lower() in ("1", "true", "yes")

    if not endpoint or not access or not secret:
        raise HTTPException(status_code=500, detail="minio env is not configured")

    return Minio(endpoint, access_key=access, secret_key=secret, secure=secure)


def _guess_data_url(content_type: Optional[str], raw: bytes) -> str:
    ct = (content_type or "").strip().lower()
    if not ct or "/" not in ct:
        ct = "image/jpeg"
    b64 = base64.b64encode(raw).decode("utf-8")
    return f"data:{ct};base64,{b64}"


def _parse_json_maybe(text: str) -> Any:
    s = (text or "").strip()
    if not s:
        return None

    if "```" in s:
        parts = s.split("```")
        for p in parts:
            p = p.strip()
            if not p:
                continue
            if p.lower().startswith("json"):
                p = p[4:].strip()
            if p.startswith("{") or p.startswith("["):
                try:
                    return json.loads(p)
                except Exception:
                    pass

    if s.startswith("{") or s.startswith("["):
        try:
            return json.loads(s)
        except Exception:
            return None

    return None


def _extract_openai_content(chat_completion: Dict[str, Any]) -> str:
    try:
        return (chat_completion.get("choices") or [])[0]["message"]["content"] or ""
    except Exception:
        return ""


# ----------------------------
# API schemas
# ----------------------------
class AnalyzeIn(BaseModel):
    bucket: Optional[str] = Field(None)
    object_key: Optional[str] = Field(None)
    media_id: Optional[str] = Field(None)
    job_id: Optional[str] = Field(None)


@router.post("/analyze")
def analyze(
    payload: AnalyzeIn,
    x_ai_internal_token: Optional[str] = Header(default=None, alias="X-AI-Internal-Token"),
    db: Session = Depends(get_db),
) -> Dict[str, Any]:
    """
    Internal worker-safe AI analyze endpoint
    """

    _require_internal_token(x_ai_internal_token)

    if not _env_bool("AI_ENABLED", default=True):
        raise HTTPException(status_code=503, detail="ai disabled")

    provider = (os.getenv("AI_PROVIDER") or "openai").strip().lower()
    if provider not in ("openai", "gateway", "mock"):
        raise HTTPException(status_code=500, detail=f"unsupported ai provider: {provider}")

    # ----------------------------
    # MOCK PROVIDER (FAST EXIT)
    # ----------------------------
    if provider == "mock":
        return {
            "provider": "mock",
            "model": "mock",
            "ms": 0,
            "title_suggested": "Mock product title",
            "description_draft": "Generated by mock AI provider",
            "attributes": {
                "color": "black",
                "material": "cotton",
                "type": "t-shirt",
            },
            "tags": ["mock", "ai", "demo"],
        }

    # ----------------------------
    # Resolve bucket/object_key
    # ----------------------------
    bucket = (payload.bucket or "").strip() if payload.bucket else ""
    object_key = (payload.object_key or "").strip() if payload.object_key else ""

    if not bucket or not object_key:
        media_id = (payload.media_id or "").strip() if payload.media_id else None
        if not media_id and payload.job_id:
            job = db.query(AIJob).filter(AIJob.id == payload.job_id).first()
            if not job:
                raise HTTPException(status_code=404, detail="job not found")
            media_id = str(job.media_id) if job.media_id else None

        if not media_id:
            raise HTTPException(status_code=422, detail="bucket/object_key or media_id/job_id is required")

        media = db.query(Media).filter(Media.id == media_id).first()
        if not media:
            raise HTTPException(status_code=404, detail="media not found")

        bucket = (media.bucket or "").strip()
        object_key = (media.object_key or "").strip()
        content_type = media.content_type
    else:
        content_type = None

    # ----------------------------
    # Read from MinIO
    # ----------------------------
    minio = _get_minio()
    try:
        resp = minio.get_object(bucket, object_key)
        try:
            raw = resp.read()
        finally:
            resp.close()
            resp.release_conn()
    except S3Error as e:
        raise HTTPException(status_code=502, detail=f"minio error: {e.code}") from e

    if not raw:
        raise HTTPException(status_code=422, detail="media content is empty")

    data_url = _guess_data_url(content_type, raw)

    # ----------------------------
    # Prompts
    # ----------------------------
    model = (os.getenv("OPENAI_MODEL") or "gpt-4o-mini").strip()
    max_tokens = int((os.getenv("OPENAI_MAX_TOKENS") or "600").strip())
    temperature = float((os.getenv("OPENAI_TEMPERATURE") or "0.2").strip())

    messages = [
        {
            "role": "system",
            "content": (
                "Ты ассистент по созданию карточек товаров. "
                "Верни ТОЛЬКО валидный JSON: "
                "{title_suggested, description_draft, attributes, tags}"
            ),
        },
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "Проанализируй изображение товара."},
                {"type": "image_url", "image_url": {"url": data_url}},
            ],
        },
    ]

    t0 = time.time()

    if provider == "openai":
        client = OpenAI(
            api_key=(os.getenv("OPENAI_API_KEY") or "").strip(),
            timeout=int((os.getenv("OPENAI_TIMEOUT_S") or "45").strip()),
        )
        r = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=temperature,
            max_tokens=max_tokens,
        )
        raw_resp = r.model_dump()

    else:  # gateway
        gw = (os.getenv("AI_GATEWAY_URL") or "").strip().rstrip("/")
        resp = requests.post(
            f"{gw}/v1/chat/completions",
            json={
                "model": model,
                "messages": messages,
                "temperature": temperature,
                "max_tokens": max_tokens,
            },
            headers={
                "Content-Type": "application/json",
                "X-AI-Internal-Token": (os.getenv("AI_INTERNAL_TOKEN") or "").strip(),
            },
            timeout=(10, int((os.getenv("AI_GATEWAY_TIMEOUT_S") or "60").strip())),
        )
        if resp.status_code >= 400:
            raise HTTPException(status_code=502, detail=f"gateway http {resp.status_code}")
        raw_resp = resp.json() or {}

    text = _extract_openai_content(raw_resp)
    parsed = _parse_json_maybe(text)

    if not isinstance(parsed, dict):
        raise HTTPException(status_code=502, detail="ai returned non-json content")

    return {
        "provider": provider,
        "model": model,
        "ms": int((time.time() - t0) * 1000),
        "title_suggested": parsed.get("title_suggested") or "Товар",
        "description_draft": parsed.get("description_draft") or "Описание будет уточнено.",
        "attributes": parsed.get("attributes") or {},
        "tags": parsed.get("tags") or [],
    }
